<?php
 return array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => '127.0.0.1',
  'DB_NAME' => 'tp5',
  'DB_USER' => 'root',
  'DB_PWD' => '',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'tour_',
  'LOG_DB_TABLE' => 'tour_logs',
  'DB_DEBUG' => true,
  'DB_FIELDS_CACHE' => true,
  'DB_CHARSET' => 'utf8',
  'DB_DEPLOY_TYPE' => 0,
  'DB_RW_SEPARATE' => false,
  'DB_MASTER_NUM' => 1,
  'DB_SLAVE_NO' => '',
  'WEBNAME' => '云系统管理平台',
  'KEYWORDS' => '云系统管理12312',
  'DISCRIPTION' => '云系统管理平台社区',
  'COPY' => 'Copyright © 2013 houdunwang.Com All Rights Reserved 后盾网',
  'RECORD' => '京ICP备10027771号-110',
  'REGIS_ON' => '0',
  'WEB_STATE' => '1',
  'KEYWRODS' => '云系统管理平台123',
);
?>